title: "[DevPlan] "
labels: ["Development Plan"]
body:
  - type: markdown
    attributes:
      value: |
        ## 1. Feature Overview
  - type: input
    id: 1-feature-name
    attributes:
      label: Feature Name
    validations:
      required: true
  - type: input
    id: 1-module
    attributes:
      label: Module
    validations:
      required: true
  - type: input
    id: 1-projects
    attributes:
      label: Projects
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 2. Objectives & Business Requirements
  - type: textarea
    id: 2-goal    
    attributes:
      label: Goal
      description: "Main objective of the feature"
      value: |
        -
    validations:
      required: true
  - type: textarea
    id: 2-functional    
    attributes:
      label: Functional
      description: "List of required functionalities"
      value: |
        1.
        2.
        3.
        -
    validations:
      required: true
  - type: textarea
    id: 2-non-functional    
    attributes:
      label: Non-functional
      description: "Performance, security, etc"
      value: |
        1.
        -
  - type: textarea
    id: 2-dependencies    
    attributes:
      label: Dependencies
      description: "Systems, APIs, etc."
      value: |
        -
    validations:
      required: true
  - type: textarea
    id: 2-constraints    
    attributes:
      label: Constraints
      description: "Any limitations"
      value: |
        -
    validations:
      required: true
  - type: textarea
    id: 2-success-metrics    
    attributes:
      label: Success Metrics
      description: "How success will be measured"
      value: |
        -
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 3. Development Scope of Work
  - type: textarea
    id: 3-tasks
    attributes:
      label: Tasks
      description: "Ticket list"
      value: |
        1.
        -
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 4. Documentation
        > Notes: Basic happy path testing to access developed features
  - type: textarea
    id: 4-user-guide
    attributes:
      label: User Guide
      description: "Instructions for users"
      value: |
        Step by step happy path testing c/o QAs and Devs
        -
    validations:
      required: true
  - type: textarea
    id: 4-technical-guide
    attributes:
      label: Technical Guide
      description: "For developers/maintainers"
      value: |
        - Try to minimize code snippets as those routinely change, focus on core functions AND their workflow logic
        - To include at least one sequence diagram or basic flowchart to visually describe flow of data/logic.
        -
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 5. (Optional) Design and Implementation
  - type: textarea
    id: 5-design-summary
    attributes:
      label: Design Summary
      description: "Brief overview of design"
      value: |
        - Can be as simple as linking Figma Design if applicable or if N/A this can be blank
        -
  - type: textarea
    id: 5-ui-ux
    attributes:
      label: UI/UX
      description: "User inferface and experience notes"
      value: |
        - Can be as simple as linking Figma Design if applicable or if N/A this can be blank
        -
  - type: textarea
    id: 5-data-model
    attributes:
      label: Data Model
      description: "Details of data model changes"
      value: |
        - This should provide overview of relationship of the data (if applicable i.e. New modules or updates to existing modules that required addition to existing features or revamp of existing features)
        -

  - type: markdown
    attributes:
      value: |
        ## 6. Testing
  - type: textarea
    id: 6-strategy
    attributes:
      label: Strategy
      description: "e.g., Unit Tests, Integration Tests"
      value: |
        -
    validations:
      required: true
  - type: textarea
    id: 6-key-test-cases
    attributes:
      label: Key Test Cases
      description: "Outline key test scenarios"
      value: |
        -
    validations:
      required: true
  - type: textarea
    id: 6-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: "Criteria for feature completion"
      value: |
        -
    validations:
      required: true
